---
# This playbook prints a simple debug message
- name: Echo Hello, Fred and Wilma
  hosts: localhost

  tasks:
  - name: "playbook1 - testing input vars"
    set_stats:
      data:
        pb_var1a: "{{ input1a }}"
        pb_var1b: "{{ input1b }}"

  - debug: msg="Hello, {{ input1a }} and {{ input1b }}"
 